2015-09-05 12:55:44,999 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 12:55:45,001 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 12:55:45,001 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 12:55:45,001 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 12:55:45,001 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 12:55:45,001 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
2015-09-05 13:00:58,697 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 13:00:58,701 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 13:00:58,701 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 13:00:58,702 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 13:00:58,702 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 13:00:58,702 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
2015-09-05 13:02:16,769 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 13:02:16,776 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 13:02:16,777 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 13:02:16,777 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 13:02:16,777 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 13:02:16,777 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
2015-09-05 13:02:52,468 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 13:02:52,471 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 13:02:52,471 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 13:02:52,471 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 13:02:52,471 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 13:02:52,472 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
2015-09-05 13:03:20,603 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 13:03:20,605 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 13:03:20,605 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 13:03:20,605 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 13:03:20,605 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 13:03:20,605 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
2015-09-05 13:03:56,266 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 1.
2015-09-05 13:03:56,268 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 2.
2015-09-05 13:03:56,268 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 3.
2015-09-05 13:03:56,268 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 4.
2015-09-05 13:03:56,268 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 5.
2015-09-05 13:03:56,268 ERROR org.apache.hadoop.mrunit.TestDriver: Received unexpected output (a, 1) at position 6.
